--- #YAML:1.0
name:               VIM-Uploader
version:            0.01
abstract:           upload your vim script to vim.org
author:
    - Cornelius <cornelius.howl@gmail.com>
license:            MIT
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    File::Spec:      0
    Test::More:      0
    WWW::Mechanize:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
